# Generated by Django 4.1.7 on 2023-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_gasto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gastos/'),
        ),
    ]
