# Generated by Django 4.1.7 on 2023-05-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_alter_gasto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='stock',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='fecha_de_carga',
            new_name='fecha_de_compra',
        ),
    ]
