# Generated by Django 4.1.7 on 2023-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_infoextra_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
